/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert adder
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert readout
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/readout/setDepth 2

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert energyResolution
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyResolution/fwhm 0.25
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert timeResolution 
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/timeResolution/fwhm 3 ns

/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/insert energyFraming
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMin 250. keV
/gate/digitizerMgr/LYSO/SinglesDigitizer/Singles/energyFraming/setMax 750. keV

# coincidence sorters, prompts + delays

/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection Singles
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow 14. ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/minSectorDifference 2  
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy takeAllGoods

/gate/digitizerMgr/name delay
/gate/digitizerMgr/insert CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setInputCollection Singles
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow 14. ns
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset 1400. ns
/gate/digitizerMgr/CoincidenceSorter/delay/minSectorDifference 2
/gate/digitizerMgr/CoincidenceSorter/delay/MultiplesPolicy takeAllGoods
