#=====================================================
#  D A T A   O U T P U T   
#=====================================================

/gate/output/root/enable
/gate/output/root/setFileName             output/output
/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag        1


#/gate/output/ascii/enable
#/gate/output/ascii/setFileName                 output/myfile
#/gate/output/ascii/setOutFileHitsFlag          0
#/gate/output/ascii/setOutFileSinglesFlag       0
#/gate/output/ascii/setOutFileCoincidencesFlag  1
#/gate/output/ascii/setOutFiledelayFlag         1
